### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by khan7869** [DarkSecDevelopers/GrayKeylogger#1]
how this program works? should I build and send the .exe file through email to victim?

**Comment by footballs** [comment]
Build exe and send victim via any mean.(doesn't matters)
Exe should run 1 time in victim pc and you will be start getting logs at your provided email.

**Comment by khan7869** [comment]
I tested it on my own computer but received anything in the email. I tested email it was working fine

**Comment by footballs** [comment]
Check the **Showrrors** checkbox to see which thing is missing.

**Comment by graysuit** [comment]
Right
@khan7869 
You need to do as @footballs mentioned.

**Comment by khan7869** [comment]
Done everything still no luck

**Comment by footballs** [comment]
@khan7869 
I can assist team viewer remotely on this issue:
mir.imran.khan999@gmail.com

**Comment by khan7869** [comment]
Not gonna take a chance with hackers to access my computer

**Comment by footballs** [comment]
That's mean you didn't used team viewer yet.

**Comment by khan7869** [comment]
I used it many times
